Original:
  source: smote_variants
  class: NoSMOTE
  params: {}

SMOTE:
  source: smote_variants
  class: SMOTE
  params: {}

Borderline_SMOTE1:
  source: smote_variants
  class: Borderline_SMOTE1
  params: {}

ADASYN:
  source: smote_variants
  class: ADASYN
  params: {}

distance_SMOTE:
  source: smote_variants
  class: distance_SMOTE
  params: {}

Safe_Level_SMOTE:
  source: smote_variants
  class: Safe_Level_SMOTE
  params: {}

MSMOTE:
  source: smote_variants
  class: MSMOTE
  params: {}

SMBOND:
  source: smote_variants
  class: SMOBD
  params: {}

SL_graph_SMOTE:
  source: smote_variants
  class: SL_graph_SMOTE
  params: {}

LVQ_SMOTE:
  source: smote_variants
  class: LVQ_SMOTE
  params: {}

ROSE:
  source: smote_variants
  class: ROSE
  params: {}

MWMOTE:
  source: smote_variants
  class: MWMOTE
  params: {}

V_SYNTH:
  source: smote_variants
  class: V_SYNTH
  params: {}

SMOTE_D:
  source: smote_variants
  class: SMOTE_D
  params: {}

CURE_SMOTE:
  source: smote_variants
  class: CURE_SMOTE
  params: {}

ASMOBD:
  source: smote_variants
  class: ASMOBD
  params: {}

G_SMOTE:
  source: smote_variants
  class: G_SMOTE
  params: {}

MDO:
  source: smote_variants
  class: MDO
  params: {}

Random_SMOTE:
  source: smote_variants
  class: Random_SMOTE
  params: {}

GASMOTE:
  source: smote_variants
  class: GASMOTE
  params: {}

SSO:
  source: smote_variants
  class: SSO
  params: {}

NDO_sampling:
  source: smote_variants
  class: NDO_sampling
  params: {}

Gaussian_SMOTE:
  source: smote_variants
  class: Gaussian_SMOTE
  params: {}

Supervised_SMOTE:
  source: smote_variants
  class: Supervised_SMOTE
  params: {}

CCR:
  source: smote_variants
  class: CCR
  params: {}

ANS:
  source: smote_variants
  class: ANS
  params: {}

cluster_SMOTE:
  source: smote_variants
  class: cluster_SMOTE
  params: {}

SYMPROD:
  source: smote_variants
  class: SYMPROD
  params: {}

SMOTE_TomekLinks:
  source: smote_variants
  class: SMOTE_TomekLinks
  params: {}

KMeans_SMOTE:
  source: smote_variants
  class: kmeans_SMOTE
  params: {}

AKMeans_SMOTE:
  source: local
  module: src.methods.classic.akmeans_smote
  class: AKMeansSMOTE
  params: {}
